export {default as Main} from "./Main/Main"
export {default as Search} from "./Search/Search"
export {default as MovieDetails} from "./MovieDetails/MovieDetails"
export {default as TvDetails} from "./TvDetails/TvDetails"
export {default as Favorite} from "./Favorite/Favorite"